Fixing OpenCV configuration related issues
scorelab/imagelab pull request #4
Opened 2020-07-06 21:02 UTC by dilum1995

## Description
This pull request contains the configuration of OpenCV to the project. Also, this solves the previous configuration issues in the maven dependencies as well.

## Type of change 
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Current Status 
<img width="1279" alt="Main Dashboard" src="https://user-images.githubusercontent.com/23298579/85952836-98985680-b989-11ea-82d5-e8fbfea4aebd.png">

2020-07-07 02:15 UTC, ivantha requested changes
Let's ignore the `workspace.xml`.

2020-07-12 05:38 UTC, dilum1995 commented
> Let's ignore the `workspace.xml`.

Actually I have added `.idea/**/workspace.xml` this to gitignore. Can't understand how it ended up here.

2020-07-13 13:57 UTC, dilum1995 commented
@ivantha shall we merge this, then I will send another draft PR which has that drag-drop related changes.

2020-07-13 14:03 UTC, ivantha approved these changes

2020-07-13 14:03 UTC, merged